### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'multiscale' while training on custom dataset

### ISSUE THREAD

**Issue by Sehjbir** [xmba15/yolov3_pytorch#2]

**Comment by xmba15** [comment]
@Sehjbir you need to specify multiscale parameter as in here if you create your own data loader.
https://github.com/xmba15/yolov3_pytorch/blob/master/data_loader/bird_dataset.py#L38

I have created data loader for multiple datasets in here. you might try to use as reference.
https://github.com/xmba15/yolov3_pytorch/tree/master/data_loader

**Comment by Sehjbir** [comment]
Yes, I was able to modify the code. This error was resolved. However, I'm facing this error now:
RuntimeError: DataLoader worker (pid(s) 5645) exited unexpectedly

Things I have done to solve this:
1) set num-workers = 1
2) set batch_size = 1

Setting num-workers = 0 pushes the code on the CPU which again results in a memory allocation error. Any help on this?
